<a href="https://colab.research.google.com/github/anjalibajpai768-cell/AI-ML-INTERNSHIP/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array = np.array([10,20,30,40,50])
print(array)

[10 20 30 40 50]


In [15]:
print(array[1:3])

[[30 40]
 [50 60]]


In [3]:
array = np.array([[10,20,30],[40,50,60]])
print(array)

[[10 20 30]
 [40 50 60]]


In [5]:
array = np.array([[10,20],[30,40],
                 [50,60],[70,80]])
print(array)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [6]:
print(array.ndim)

2


In [7]:
print(array.shape)

(4, 2)


In [9]:
print(array.shape)
print(array.size)
print(array.dtype)

(4, 2)
8
int64


In [10]:
print(array[2])

[50 60]


In [14]:
print(array[1,1])

40


In [37]:
a = np.array([10,20,30])
b = np.array([40,50,60])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.sqrt(a))
print(np.power(a,2))
print(array)

[50 70 90]
[-30 -30 -30]
[ 400 1000 1800]
[0.25 0.4  0.5 ]
[3.16227766 4.47213595 5.47722558]
[100 400 900]
[10 20 30]


In [39]:
arr = np.array([10,20,30,40,50])
print(np.mean(arr))   #to find the average
print(np.median(arr))  #to find median value
print(np.std(arr))   #standard deviation
print(np.max(arr))  #highest value
print (np.min(arr) ) #lowest value
print(np.sum(arr))  #total value
print(np.cumsum(arr)) #cumulative sum
print(np.var(arr))  #variance
# Corrected: To reshape an array, you need to provide an array and a shape compatible with its size.
# For example, to reshape 'arr' (5 elements) into a (5,1) column vector:
print(arr.reshape(5,1))
print(arr.flatten())

30.0
30.0
14.142135623730951
50
10
150
[ 10  30  60 100 150]
200.0
[[10]
 [20]
 [30]
 [40]
 [50]]
[10 20 30 40 50]


In [40]:
arr = np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]


In [41]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.arange(1,11)  #array in particular range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
np.random.rand(5)   #give random numbers below 1

array([0.53968151, 0.28515698, 0.81477061, 0.16438854, 0.52172931])

In [49]:
np.random.randint(1,100,10)  #gives random integers

array([58, 10, 24, 57, 87, 47, 29, 22, 72, 61])